name: 'Poc workflow'

# **What it does**: checks the files pushed into main branch and prints the files recently modified.

on:
  push:
    branches:
      - main
   # paths:
   #   - '**IL'
  pull_request:
    branches:
      - main
    #paths:
    #  - '**IL'

jobs:
  check-out-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all added/modified IL files
        #shell: bash
        id: list-IL-files
        run: |
          echo "1"
          export var_il_list=
          echo "2"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "${file} was changed"
            if [ "`echo ${file} | rev | cut -c 1-3 | rev`" = ".IL" ]; then
             echo "3"
              export var_il_list=`echo ${var_il_list} ${file}`
            fi
            echo "4"
          done
          echo ${var_il_list}
        env:
          var_il_list: ${{ steps.list-IL-files.outputs.var_il_list }}
          
      - name: Validate script names in IL files
        run: |
          var_il_list=${{ steps.list-IL-files.outputs.var_il_list }}
          echo "IL LIST: ${var_il_list}"
          if [ "${var_il_list}" != "" ]; then
            for il in ${var_il_list}
            do
              export err=0
              for fname in ${il}
              do
                var_file=`echo ${fname} | awk -F: '{print $2}'`
                if [ `ls ${var_file} | wc -l` -eq 0 ]; then
                 echo ${il}: ${var_file} does not exists
                 export err=`expr ${err} + 1`
                fi
              done
             done
             echo "err: ${err}"
             if [ "${err}" = "0" ]; then
               echo "IL validation completed successfully..."
             else
               echo "Errors while validating IL files"
               exit 1
             fi
          else
            echo "Skipping validation..."
          fi
          
      - name: Create build for each IL
        run: |
          var_il_list=${{ steps.list-IL-files.outputs.var_il_list }}
          export builds=
          if [ "${var_il_list}" != "" ]; then
            for j in ${var_il_list}
            do
              tar_name=`echo ${j} | awk -F. '{print $1}'`.tar
              for f1 in ${il}
              do
                var_file=`echo ${fname} | awk -F: '{print $2}'`
                export var_files=`echo ${var_files} ${var_file}`
              done
              tar -cf ${tar_name} ${var_files}
              if [ $? -eq 0 ]; then
                export builds=`echo ${builds} ${tar_name}`
              else
                echo "Error while creating ${tar_name}"
                exit 1
              fi
             done
             echo "Builds created successfully: ${builds}"
           else
             echo "Skipping build creation..."
           fi
